# Generated by Django 5.2.6 on 2025-09-19 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_course_duraction_month_course_is_online_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategoriya'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='school_cate_name_6e86ab_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duraction_month',
        ),
        migrations.AddField(
            model_name='course',
            name='duration_months',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beg', 'Beginner'), ('int', 'Intermediate'), ('adv', 'Advanced')], default='beg', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_students',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, help_text='300x300 px tavsiya etiladi', null=True, upload_to='teachers/'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='school_cour_title_c95d53_idx'),
        ),
    ]
