# Generated by Django 5.2.7 on 2025-10-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_category_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='school_cour_title_c95d53_idx',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('title', 'category'), name='unique_course_per_category'),
        ),
    ]
